[theme]
primaryColor = "#4cd137"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f0f0"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true